In [1]:
# Step 1: Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", plt.matplotlib.__version__)
print("Seaborn:", sns.__version__)

Pandas: 3.0.6
NumPy: 2.5.3
Matplotlib: 3.11.2
Seaborn: 0.13.2

In [3]:
%pip install matplotlib seaborn pandas numpy openpyxl

Requirement already satisfied: matplotlib in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: pandas in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (2.5.3)
Requirement already satisfied: openpyxl in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\ganesh koli\appdata\roaming\python\python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ganesh koli\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: et-xmlfile in c:\users\ganesh koli\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\ganesh koli\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Step 2: Load the dataset

file_path = "../data/raw/ApexPlanet_DataAnalytics_Dataset.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="Sales_Dataset"
)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [6]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83

In [7]:
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 1000
Total columns: 12

In [8]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   str
 1   Order_Date     1000 non-null   str
 2   Customer_ID    1000 non-null   str
 3   Customer_Name  1000 non-null   str
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   str
 6   City           987 non-null    str
 7   Product        1000 non-null   str
 8   Category       1000 non-null   str
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), str(8)
memory usage: 93.9 KB

In [10]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Order_ID,1000,992,ORD100050,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order_Date,1000,342,2025-04-16,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_ID,1000,947,CUST2515,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Name,1000,425,Customer_359,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,980.0,NaN,NaN,NaN,41.360204,13.822597,18.0,30.0,41.0,54.0,65.0
Gender,1000,2,Male,511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,987,8,Patna,135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,1000,6,Mobile,184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,1000,5,Electronics,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,1000.0,NaN,NaN,NaN,5.435,2.838632,1.0,3.0,5.0,8.0,10.0
Unit_Price,1000.0,NaN,NaN,NaN,25486.78341,14179.402361,145.78,13895.7225,25398.74,37512.3825,49997.53
Total_Sales,1000.0,NaN,NaN,NaN,139399.43965,114100.051546,437.34,47066.6325,108594.025,203722.8825,493677.5

In [ ]:
# DAY 2

In [11]:

# Day 2

import pandas as pd
import numpy as np
import os

if "df" not in globals():
    raise NameError(
        "Dataset not loaded. Complete Day 1 and load the dataset into df first."
    )

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Number of rows: 1000
Number of columns: 12

Column names:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales']

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [12]:

# Day 2 Create the data dictionary

dictionary_data = [
    {
        "Column": "Order_ID",
        "Description": "Unique identifier of an order",
        "Expected_Type": "Text",
        "Validation_Rule": "Should not be missing; check uniqueness"
    },
    {
        "Column": "Order_Date",
        "Description": "Date when the order was placed",
        "Expected_Type": "Date",
        "Validation_Rule": "Should contain valid dates"
    },
    {
        "Column": "Customer_ID",
        "Description": "Identifier of the customer",
        "Expected_Type": "Text",
        "Validation_Rule": "Check for missing values"
    },
    {
        "Column": "Customer_Name",
        "Description": "Name of the customer",
        "Expected_Type": "Text",
        "Validation_Rule": "Check for missing or inconsistent names"
    },
    {
        "Column": "Age",
        "Description": "Age of the customer",
        "Expected_Type": "Numeric",
        "Validation_Rule": "Check missing values and reasonable age range"
    },
    {
        "Column": "Gender",
        "Description": "Gender category recorded in the dataset",
        "Expected_Type": "Text",
        "Validation_Rule": "Check missing values and inconsistent labels"
    },
    {
        "Column": "City",
        "Description": "City associated with the customer or order",
        "Expected_Type": "Text",
        "Validation_Rule": "Check missing values and spelling variations"
    },
    {
        "Column": "Product",
        "Description": "Name of the product purchased",
        "Expected_Type": "Text",
        "Validation_Rule": "Check missing or inconsistent product names"
    },
    {
        "Column": "Category",
        "Description": "Category to which the product belongs",
        "Expected_Type": "Text",
        "Validation_Rule": "Check category consistency"
    },
    {
        "Column": "Quantity",
        "Description": "Number of units purchased",
        "Expected_Type": "Integer",
        "Validation_Rule": "Should be numeric and usually greater than zero"
    },
    {
        "Column": "Unit_Price",
        "Description": "Price of one unit of the product",
        "Expected_Type": "Numeric",
        "Validation_Rule": "Should be numeric and non-negative"
    },
    {
        "Column": "Total_Sales",
        "Description": "Total sales amount for the order line",
        "Expected_Type": "Numeric",
        "Validation_Rule": "Compare against Quantity multiplied by Unit_Price"
    }
]

data_dictionary = pd.DataFrame(dictionary_data)

# Keep only definitions for columns actually present in the dataset
data_dictionary = data_dictionary[
    data_dictionary["Column"].isin(df.columns)
].copy()

# Identify any dataset columns that still need definitions
undefined_columns = [
    col for col in df.columns
    if col not in data_dictionary["Column"].tolist()
]

print("Data dictionary created!")
print("Documented columns:", len(data_dictionary))
print("Columns needing definitions:", undefined_columns)

display(data_dictionary)

Data dictionary created!
Documented columns: 12
Columns needing definitions: []

,Column,Description,Expected_Type,Validation_Rule
0,Order_ID,Unique identifier of an order,Text,Should not be missing; check uniqueness
1,Order_Date,Date when the order was placed,Date,Should contain valid dates
2,Customer_ID,Identifier of the customer,Text,Check for missing values
3,Customer_Name,Name of the customer,Text,Check for missing or inconsistent names
4,Age,Age of the customer,Numeric,Check missing values and reasonable age range
5,Gender,Gender category recorded in the dataset,Text,Check missing values and inconsistent labels
6,City,City associated with the customer or order,Text,Check missing values and spelling variations
7,Product,Name of the product purchased,Text,Check missing or inconsistent product names
8,Category,Category to which the product belongs,Text,Check category consistency
9,Quantity,Number of units purchased,Integer,Should be numeric and usually greater than zero
10,Unit_Price,Price of one unit of the product,Numeric,Should be numeric and non-negative
11,Total_Sales,Total sales amount for the order line,Numeric,Compare against Quantity multiplied by Unit_Price

In [13]:

# Day 2 - Step 4: Inspect actual data types

type_profile = pd.DataFrame({
    "Column": df.columns,
    "Actual_Data_Type": df.dtypes.astype(str).values,
    "Non_Null_Count": df.notna().sum().values,
    "Missing_Count": df.isna().sum().values,
    "Unique_Values": df.nunique(dropna=True).values
})

print("Column profile:")
display(type_profile)

Column profile:

,Column,Actual_Data_Type,Non_Null_Count,Missing_Count,Unique_Values
0,Order_ID,str,1000,0,992
1,Order_Date,str,1000,0,342
2,Customer_ID,str,1000,0,947
3,Customer_Name,str,1000,0,425
4,Age,float64,980,20,48
5,Gender,str,1000,0,2
6,City,str,987,13,8
7,Product,str,1000,0,6
8,Category,str,1000,0,5
9,Quantity,int64,1000,0,10
10,Unit_Price,float64,1000,0,1000
11,Total_Sales,float64,1000,0,1000

In [14]:

# Day 2 - Step 5: Numerical summary

print("Numerical columns:")
display(df.describe())

print("\nCategorical columns:")
display(df.describe(include="object"))

Numerical columns:

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

Categorical columns:

C:\Users\GANESH KOLI\AppData\Local\Temp\ipykernel_16536\2467292525.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include="object"))

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,City,Product,Category
count,1000,1000,1000,1000,1000,987,1000,1000
unique,992,342,947,425,2,8,6,5
top,ORD100050,2025-04-16,CUST2515,Customer_359,Male,Patna,Mobile,Electronics
freq,9,10,3,8,511,135,184,354

In [15]:

# Day 2 - Step 6: Save deliverables

os.makedirs("../reports", exist_ok=True)

dictionary_path = "../reports/data_dictionary.csv"
profile_path = "../reports/column_profile.csv"

data_dictionary.to_csv(dictionary_path, index=False)
type_profile.to_csv(profile_path, index=False)

print("Day 2 deliverables saved successfully!")
print("Data dictionary:", os.path.abspath(dictionary_path))
print("Column profile:", os.path.abspath(profile_path))

Day 2 deliverables saved successfully!
Data dictionary: d:\ApexPlanet-Task-1\reports\data_dictionary.csv
Column profile: d:\ApexPlanet-Task-1\reports\column_profile.csv

In [ ]:
# DAY 3

In [16]:
import pandas as pd
import numpy as np
import os

# Verify that the dataset is available
if "df" not in globals():
    raise NameError(
        "Please load your dataset into a DataFrame named df first."
    )

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
display(df.head())

Dataset loaded successfully!
Rows: 1000
Columns: 12

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [17]:
# Step 2: Missing values report

missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (
        df.isna().mean().values * 100
    ).round(2),
    "Non_Missing_Count": df.notna().sum().values
})

missing_report = missing_report.sort_values(
    "Missing_Count",
    ascending=False
)

display(missing_report)

           Column  Missing_Count  Missing_Percentage  Non_Missing_Count
4             Age             20                 2.0                980
6            City             13                 1.3                987
0        Order_ID              0                 0.0               1000
1      Order_Date              0                 0.0               1000
3   Customer_Name              0                 0.0               1000
2     Customer_ID              0                 0.0               1000
5          Gender              0                 0.0               1000
7         Product              0                 0.0               1000
8        Category              0                 0.0               1000
9        Quantity              0                 0.0               1000
10     Unit_Price              0                 0.0               1000
11    Total_Sales              0                 0.0               1000

In [18]:
# Step 3: Find exact duplicate rows

duplicate_count = df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

duplicate_rows = df[df.duplicated(keep=False)].copy()

print("Rows involved in duplicates:", len(duplicate_rows))
display(duplicate_rows.head(10))

Total duplicate rows: 0
Rows involved in duplicates: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [19]:
# Step 4: Check duplicate IDs if the column exists

if "Order_ID" in df.columns:
    duplicate_id_mask = df["Order_ID"].duplicated(keep=False)

    print("Rows with repeated Order_ID values:",
          duplicate_id_mask.sum())

    display(
        df.loc[duplicate_id_mask]
          .sort_values("Order_ID")
          .head(20)
    )
else:
    print("Order_ID column not found.")

Rows with repeated Order_ID values: 9

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

In [20]:
# Step 5: Inspect data types

dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": df.nunique(dropna=True).values
})

display(dtype_report)

           Column Data_Type  Unique_Values
0        Order_ID       str            992
1      Order_Date       str            342
2     Customer_ID       str            947
3   Customer_Name       str            425
4             Age   float64             48
5          Gender       str              2
6            City       str              8
7         Product       str              6
8        Category       str              5
9        Quantity     int64             10
10     Unit_Price   float64           1000
11    Total_Sales   float64           1000

In [21]:
# Step 6: Check numerical ranges

numeric_checks = {
    "Age": lambda s: (s < 0) | (s > 120),
    "Quantity": lambda s: s <= 0,
    "Unit_Price": lambda s: s < 0,
    "Total_Sales": lambda s: s < 0
}

for column, rule in numeric_checks.items():
    if column in df.columns:
        values = pd.to_numeric(df[column], errors="coerce")
        invalid_mask = rule(values) & values.notna()

        print(f"\n{column} - suspicious values: {invalid_mask.sum()}")
        display(df.loc[invalid_mask].head(10))

Age - suspicious values: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

Quantity - suspicious values: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

Unit_Price - suspicious values: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

Total_Sales - suspicious values: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [22]:
# Step 7: Inspect categorical columns

categorical_columns = [
    "Gender", "City", "Product", "Category"
]

for column in categorical_columns:
    if column in df.columns:
        print(f"\n--- {column} ---")
        print("Unique values:", df[column].nunique(dropna=True))
        display(
            df[column]
              .value_counts(dropna=False)
              .head(20)
        )

--- Gender ---
Unique values: 2

Gender
Male      511
Female    489
Name: count, dtype: int64

--- City ---
Unique values: 8

City
Patna        135
Kolkata      133
Mumbai       131
Hyderabad    125
Delhi        125
Bengaluru    122
Gaya         117
Pune          99
NaN           13
Name: count, dtype: int64

--- Product ---
Unique values: 6

Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

--- Category ---
Unique values: 5

Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64

In [23]:
# Step 8: Validate sales calculations

required_columns = ["Quantity", "Unit_Price", "Total_Sales"]

if all(column in df.columns for column in required_columns):
    quantity = pd.to_numeric(df["Quantity"], errors="coerce")
    unit_price = pd.to_numeric(df["Unit_Price"], errors="coerce")
    total_sales = pd.to_numeric(df["Total_Sales"], errors="coerce")

    expected_sales = quantity * unit_price

    valid_rows = (
        quantity.notna()
        & unit_price.notna()
        & total_sales.notna()
    )

    mismatch = (
        (total_sales - expected_sales).abs() > 0.02
    ) & valid_rows

    print("Rows checked:", valid_rows.sum())
    print("Sales calculation mismatches:", mismatch.sum())

    display(
        df.loc[mismatch, required_columns].head(10)
    )
else:
    print("One or more sales columns are missing.")

Rows checked: 1000
Sales calculation mismatches: 0

Empty DataFrame
Columns: [Quantity, Unit_Price, Total_Sales]
Index: []

In [24]:
# Step 9: Create the data quality summary

quality_checks = []

for column in df.columns:
    missing_count = int(df[column].isna().sum())

    quality_checks.append({
        "Check": f"Missing values - {column}",
        "Issue_Count": missing_count,
        "Status": "Review required" if missing_count else "Pass"
    })

quality_checks.extend([
    {
        "Check": "Exact duplicate rows",
        "Issue_Count": int(df.duplicated().sum()),
        "Status": "Review required" if df.duplicated().sum() else "Pass"
    }
])

if "Order_ID" in df.columns:
    duplicate_ids = int(
        df["Order_ID"].duplicated(keep=False).sum()
    )

    quality_checks.append({
        "Check": "Rows with repeated Order_ID",
        "Issue_Count": duplicate_ids,
        "Status": "Review required" if duplicate_ids else "Pass"
    })

data_quality_report = pd.DataFrame(quality_checks)

display(data_quality_report)

                             Check  Issue_Count           Status
0        Missing values - Order_ID            0             Pass
1      Missing values - Order_Date            0             Pass
2     Missing values - Customer_ID            0             Pass
3   Missing values - Customer_Name            0             Pass
4             Missing values - Age           20  Review required
5          Missing values - Gender            0             Pass
6            Missing values - City           13  Review required
7         Missing values - Product            0             Pass
8        Missing values - Category            0             Pass
9        Missing values - Quantity            0             Pass
10     Missing values - Unit_Price            0             Pass
11    Missing values - Total_Sales            0             Pass
12            Exact duplicate rows            0             Pass
13     Rows with repeated Order_ID            9  Review required

In [25]:
# Step 10: Save Day 3 reports

os.makedirs("../reports", exist_ok=True)

missing_report.to_csv(
    "../reports/missing_values_report.csv",
    index=False
)

duplicate_rows.to_csv(
    "../reports/duplicate_rows.csv",
    index=False
)

data_quality_report.to_csv(
    "../reports/data_quality_report.csv",
    index=False
)

print("Day 3 reports saved successfully!")
print("Reports folder:", os.path.abspath("../reports"))

Day 3 reports saved successfully!
Reports folder: d:\ApexPlanet-Task-1\reports